### PR TITLE
mariadb:start creates container from config

### PR DESCRIPTION
**Pull request by ignlg**
If no container is found, creates a new one with the existing configuration.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Note: this needs to be done on all plugins.

**Comment by Flink** [comment]
@ignlg There’s a lot of similar code between `create` and the `service_start` function. Wouldn’t be better if all the logic were in the `service_start` function and the `create` command would just call it?
Then the function will just start the container if it already exists and otherwise it would create a container (creating necessary config files if needed else just read them if they already exists).

What do you think?

**Comment by ignlg** [comment]
You're right, I thought about it after the commit too but I preferred to have some feedback first. Hold this pull until my next commit.

**Comment by ignlg** [comment]
Hummm, I need to investigate that failed test.

**Comment by Flink** [comment]
@ignlg Could you rebase your code against latest master please? And is your code done? :)

**Comment by ignlg** [comment]
There are failed tests due to the shared state between tests, afaik, but I couldn't fix them yet. Anyway, I'll rebase this PR right now :)

**Comment by Flink** [comment]
@ignlg yeah I fixed the failing tests on all plugins. That’s strange my latest commit appears in your PR if you rebased against master, no? And I think you may have some tests to fix now ;)

**Comment by ignlg** [comment]
origin/master was behind upstream/master, my fault. Clean tree using the dark side :-) Time to check those tests.

**Comment by ignlg** [comment]
It's an error with the tests environment. The service `dokku.mariadb.l` already exists when the `service_create.bats` test starts. If I replace the service name `l` with a different string, it works:

With:
```bash
#!/usr/bin/env bats
load test_helper

@test "($PLUGIN_COMMAND_PREFIX:create) success" {
  run dokku "$PLUGIN_COMMAND_PREFIX:create" xxx
  assert_contains "${lines[*]}" "container created: xxx"
}

@test "($PLUGIN_COMMAND_PREFIX:create) error when there are no arguments" {
  run dokku "$PLUGIN_COMMAND_PREFIX:create"
  assert_contains "${lines[*]}" "Please specify a name for the service"
}
```
the result is:
```
# bats tests/service_create.bats
 ✓ (mariadb:create) success
 ✓ (mariadb:create) error when there are no arguments

2 tests, 0 failures
```

**Comment by ignlg** [comment]
@Flink _bump_. Are tests wrong? What should I do?

**Comment by Flink** [comment]
Ah yes sorry! Hmm seems the tests are failing on Travis. The file `ID` is not present on logs. And I don’t think you should have to change the test for `xxx` instead of `l`. It might indicate there’s a slight problem with your implementation maybe?

**Pull request closed without merging**
